### ISSUE TITLE
Accept request bug

### ISSUE THREAD

**Issue by DiogoParrinha** [MeetAbroad/Server#14]
When accepting a friend request and the user switches to the 'Connections' tab quickly, one of  the rows is collapsed by a timer JS function.

Check if the counter decreases as well.

**Comment by andreasluca** [comment]
True, i am dealing with it, but i will leave it for sprint 3

**Comment by DiogoParrinha** [comment]
I think this is finished. I've done some improvements on the controllers interaction and everything seems to work fine.
